.Dd August 27, 2017
.Dt vdtui 1 URM
.Os Linux/MacOS
.
.
.Sh NAME
.
.Nm vdtui
.Nd a Python3 module for data-oriented text user interfaces
.
.Sh DESCRIPTION
.
.Nm vdtui
is a single-file Python3 module for building text user interface workflows.
.
.Sh COMMANDS
.
.so vdtui-keystrokes.inc
.
.Sh OPTIONS
.
These options are common to all vdtui applications.

.
.Bl -tag -width XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -compact
.so vdtui-menu.inc
.El
.
.Sh SEE ALSO
.
.Xd vd 1
.
.
.Sh AUTHOR
.
.Nm vdtui
was created by
.An Saul Pwanson Aq Mt visidata@saul.pw
