site_name: VisiData v0.41
site_description: A curses interface for exploring and arranging tabular data
site_author: Saul Pwanson

repo_url: github.com/saulpw/visidata

pages:
- Home: index.md
- User Guide: user-guide.md
- About:
    - Credits and Inspiration: about/credits.md
    - Contributing: about/contributing.md
