#!/usr/bin/env python3

import os.path
import sys
import subprocess
from visidata import Sheet, Column, ColumnAttr, Path, ENTER, asyncthread, vd, TextSheet
from visidata import *

import git

@VisiData.api
def git_log(vd, args, topsheet):
    return git.GitLogSheet(topsheet.branch+"_log", ref=topsheet.branch, source=topsheet)

@VisiData.api
def git_status(vd, args, topsheet):
    return git.GitStatus(topsheet.source)

@VisiData.api
def git_blame(vd, args, topsheet):
    return git.GitBlame(GitFile(args[0]), source=topsheet)

vd.addGlobals(globals())

if __name__ == '__main__':
    vd.status(__version_info__)
    rc = main()
    sys.exit(rc)
