.Sh Glossary
.
.Bl -tag -width XXXXXXXXX -compact
.It Ql abort
exit program immediately
.It Ql drop
drop top (current) sheet
.It Ql go
move cursor
.It Ql jump
change to existing sheet
.It Ql load
reload an existing sheet from in-memory contents
.It Ql move
change layout of visible data
.It Ql open
push a sheet to top of sheets list (making it immediately visible)
.It Ql scroll
change set of visible rows
.It Ql show
output to status line
.It Ql this
current [row/column/cell] ('current' is also used)
