.It Sy "disp_truncator    " No "…               "
 
.It Sy "disp_key_sep      " No "/               "
 
.It Sy "disp_format_exc   " No "?               "
 
.It Sy "disp_getter_exc   " No "!               "
 
.It Sy "disp_edit_fill    " No "_               "
edit field fill character 
.It Sy "disp_more_left    " No "<               "
display cue in header indicating more columns to the left 
.It Sy "disp_more_right   " No ">               "
display cue in header indicating more columns to the right 
.It Sy "disp_column_sep   " No "|               "
chars between columns 
.It Sy "disp_keycol_sep   " No "‖               "
chars between keys and rest of columns 
.It Sy "disp_error_val    " No "¿               "
displayed contents when getter fails due to exception 
.It Sy "disp_none         " No "                "
visible contents of a cell whose value was None 
.It Sy "color_current_row " No "reverse         "
 
.It Sy "color_default     " No "normal          "
 
.It Sy "color_selected_row" No "215 yellow      "
 
.It Sy "color_format_exc  " No "48 bold yellow  "
 
.It Sy "color_getter_exc  " No "red bold        "
 
.It Sy "color_current_col " No "bold            "
 
.It Sy "color_current_hdr " No "reverse underline"
 
.It Sy "color_key_col     " No "81 cyan         "
 
.It Sy "color_default_hdr " No "bold underline  "
 
.It Sy "color_column_sep  " No "246 blue        "
 
.It Sy "disp_status_sep   " No " |              "
string separating multiple statuses 
.It Sy "disp_unprintable  " No ".               "
a substitute character for unprintables 
.It Sy "disp_column_fill  " No "                "
pad chars after column value 
.It Sy "disp_oddspace     " No "·               "
displayable character for odd whitespace 
.It Sy "color_status      " No "bold            "
status line color 
.It Sy "color_edit_cell   " No "normal          "
edit cell color 
.It Sy "disp_status_fmt   " No "{sheet.name}|   "
status line prefix 
.It Sy "disp_ambig_width  " No "1               "
width to use for unicode chars marked ambiguous 
.It Sy "disp_histogram    " No "*               "
 
.It Sy "disp_histolen     " No "80              "
width of histogram column 
