.Dd August 27, 2017
.Dt vd 1 URM
.Os Linux/MacOS
.
.
.Sh NAME
.
.Nm VisiData
.Nd a terminal interface for exploring and arranging tabular data
.
.
.Sh SYNOPSIS
.
.Bl -inset -width XXXXXXXXXXXXXXXXXXXXXXXXX -compact
.It Ic vd
.Op <options>
<input> ...
.
.It Ic vd
.Op <options>
.Sy Fl p No <cmdlog.vd>
.Op Fl -batch
.Op Fl -delay No <delay>
.Op Fl -output No <output>
--
.Op Fl "-<field>=<value> ..."
.
.It <command> | 
.Sy vd
.Op <options>
.
.Sh DESCRIPTION
.
.Nm VisiData
is a text user interface for surveying, cleaning, editing, and restructuring data from any supported source, including tsv, csv, xlsx, hdf5, and sqlite.
Rows can be selected, filtered, and grouped; columns can be rearranged, transformed, and derived via regex or Python expressions; workflows can be documented, communicated, and replayed via the commandlog.
.Nm VisiData No is built on the
.Sy vdtui No platform.
.
.Sh REPLAY MODE
.Bl -tag -width XXXXXXXXXXXXXXX -compact
.It Fl "p, --play"
.No Replays a saved Ar cmdlog.vd No via curses.
.No Python format strings (like \&"{ Ns Ar field Ns }\&") No are replaced with the Ar value No given on the command line.  These format options must be specified after the --.

.It Fl -batch
replay in batch mode (without curses).

.It Fl -delay Ar delay
replay via curses with Ar delay No seconds between commands

.It Fl -output
save the final visible sheet to <output> at the end of the replay

.It Sy While replaying
.El
.Bl -tag -width XXXXXXXXXXXXXXXXXXXXXXXXX -compact -offset XXX
.It Sy ^U
pauses/resumes replay
.It Sy Space
while plaused, transitions to next step in replay
.El
.Sh COMMANDS
.so vd-keystrokes.inc
.
.Sh MAJOR OPTIONS
.Bl -tag -width XXXXXXXXXXXXXXXXXXXXXXXXX -compact
.
.It Fl f, -filetype Ns = Ns Ar filetype
use loader for
.Ar filetype
instead of file extension
.It Fl "r, --readonly"
disables editing
.It Fl y, -confirm_overwrite Ns =F
overwrites existing files without confirmation 
.El
.Sh MINOR OPTIONS
.Bl -tag -width XXXXXXXXXXXXXXXXXXXXXXXXX -compact
.so vd-cli.inc
.El
.
.Sh OPTIONS MENU
.Bl -tag -width XXXXXXXXXXXXXXXXXXXXXXXXX -compact
.so vd-menu.inc
.El
.
.
.Sh SEE ALSO
.
.Xr vdtui 7
vdtutor
.Pa /usr/share/doc/visidata/ascii-commands.txt
.
.Sh AUTHOR
.
.Nm VisiData
was created by 
.An Saul Pwanson Aq Mt visidata@saul.pw
