.Dd August 27, 2017
.Dt vd 1 URM
.Os Linux/MacOS
.
.
.Sh NAME
.
.Nm VisiData
.Nd a terminal utility for exploring and arranging tabular data
.
.
.Sh SYNOPSIS
.
.Bl -inset -width XXXXXXXXXXXXXXXXXXXXXXXXX -compact
.It Ic vd
.Op <options>
<input> ...
.
.It Ic vd
.Op <options>
.Sy Fl p No <cmdlog.vd>
.Op Fl -batch
.Op Fl -delay No <delay>
.Op Fl o No <output>
.
.It <command> | 
.Sy vd
.Op <options>
.
.Sh DESCRIPTION
.
.Nm VisiData
is a multipurpose tool for exploring, cleaning, editing, and restructuring data from supported sources, including tsv, csv, xlsx, hdf5, and sqlite.
Rows can be selected, filtered, and grouped; columns can be rearranged, transformed, and derived via regex or Python expressions; workflows can be documented, communicated, and replayed via the commandlog.
.Nm VisiData No is built on the
.Sy vdtui No platform.
.
.Sh REPLAY MODE
.Bl -tag -width XXXXXXXXXXXXXXXXXX -compact
.It Fl "p, --play" Ar cmdlog No
.No replays a saved Ar cmdlog.vd No within the interface

.It Fl -batch
replays in batch mode (with no interface and all output to stdout)

.It Fl -delay Ar seconds
.No delays Ar seconds No between commands

.It Fl "o, --output" Ar file No
.No saves the final visible sheet to Ar file No (as .tsv) at the end of the replay

.It Sy While Replaying
.El
.Bl -tag -width XXXXXXXXXXXXXXX -compact -offset XXX
.It Sy ^U
pauses/resumes replay
.It Sy Space
executes next row in the replaying sheet
.El
.Sh MAJOR OPTIONS
.Bl -tag -width XXXXXXXXXXXXXXXXXXXXXXXXX -compact
.
.It Fl f, -filetype Ns = Ns Ar filetype
use loader for
.Ar filetype
instead of file extension

.It Fl "r, --readonly"
disables editing

.It Fl y, -confirm_overwrite Ns =F
overwrites existing files without confirmation 
.El
.Sh COMMANDS
.so vd-keystrokes.inc
.
.Sh MINOR OPTIONS
.Bl -tag -width XXXXXXXXXXXXXXXXXXXXXXXXX -compact
.so vd-cli.inc
.El
.
.Sh OPTIONS MENU (Shift-O)
.Bl -tag -width XXXXXXXXXXXXXXXXXXXXXXXXX -compact
.so vd-menu.inc
.El
.

.Sh .visidatarc
For customizing
.Nm VisiData
settings which persist across every session.
A sample
.Sy .visidatarc
is:
.Bd -literal
options.color_key_col="cyan"
options.min_memory_mb=100
.Ed

This configures key coloumns to be colored 'cyan' and for visidata to stop loading and async processing unless 100 mb of memory are available.
.so vd-input.inc
.so glossary.inc
.
.Sh SEE ALSO
.
.Xr vdtui 7
vdtutor
.Pa /usr/share/doc/visidata/ascii-commands.txt
.
.Sh AUTHOR
.
.Nm VisiData
was created by 
.An Saul Pwanson Aq Mt visidata@saul.pw
