.Sh Other Commands
.
.Bl -tag -width XXXXXXXXXXXXXXX -compact
.
.It Ic Shift-V
views contents of current cell in a new sheet
.It Ic " ^^ (Ctrl-^)"
jumps to previous sheet (swaps with current sheet)
.It Ic "  ` (backtick)"
opens source of current sheet
.It Ic " ^E"
views traceback for most recent error
.It Ic "z^E"
views traceback for error in current cell
.It Ic " ^L"
refreshes screen
.It Ic " ^G"
shows cursor position and bounds of current sheet on status line
.It Ic " ^V"
shows version information on status line
.It Ic " ^R"
reloads current sheet
.
.El
