.Sh Other commands
.
.Bl -tag -width XXXXXXXXXXXXXXX -compact
.
.It Ic Shift-V
opens readonly view of contents of current cell
.It Ic "^^ (Ctrl-^)"
jumps to previous sheet
.It Ic " ^E"
opens traceback for most recent error
.It Ic z^E
opens traceback for error in current cell
.It Ic " ` (backtick)"
opens source of current sheet
.It Ic ^L
refreshes screen
.It Ic ^G
shows cursor position and bounds of current sheet
.It Ic ^V
shows version information
.It Ic ^R
reloads current sheet
.It Ic ^D
toggles debug mode (aborts program on any exception)
.
.El
