name: visidata-ci-build
on:
  pull_request:
    branches:
      - stable
      - develop
  push:
    branches:
    - stable
    - develop

jobs:
  full-tests:

    strategy:
      matrix:
        python-version: ["3.9", "3.14"]

    runs-on: ubuntu-slim
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install en_US.UTF-8 locale
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y locales
        sudo locale-gen en_US.UTF-8

    - name: Install VisiData with test dependencies
      run: make install-test

    - name: Run tests
      run: make test

  unit-tests:

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install en_US.UTF-8 locale
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y locales
        sudo locale-gen en_US.UTF-8

    - name: Install VisiData with test dependencies
      run: make install-test

    - name: Run unit tests
      run: make test
